/* linanqinqin */  
// gen_lame_data_offsets.c
#include <stdio.h>
#include <stddef.h>
// Use kernel-style include path for host tool
#include <asm/vdso/lame_data.h>

int main(void) {
    printf("/* linanqinqin */\n");
    printf("/* This file is auto-generated by gen_lame_data_offsets.c */\n");
    printf("/* Do not edit this file manually!!! */\n");
    printf("#ifndef LAME_DATA_ASM_H\n#define LAME_DATA_ASM_H\n\n");

    // struct lame_handle
    printf("#define LAME_HANDLE_SIZE %zu\n", sizeof(struct lame_handle));
    printf("#define LAME_HANDLE_ACTIVE %zu\n", offsetof(struct lame_handle, active));
    printf("#define LAME_HANDLE_CTX %zu\n", offsetof(struct lame_handle, ctx));
    printf("#define LAME_HANDLE_SWITCH_COUNT %zu\n", offsetof(struct lame_handle, switch_count));
    printf("#define LAME_HANDLE_BUNDLE_ID %zu\n", offsetof(struct lame_handle, bundle_id));
    printf("#define LAME_HANDLE_LAST_SWITCH_TSC %zu\n", offsetof(struct lame_handle, last_switch_tsc));
    printf("#define LAME_HANDLE_CPU_ID %zu\n\n", offsetof(struct lame_handle, cpu_id));

    // struct lame_ctx
    printf("#define LAME_CTX_SIZE %zu\n", sizeof(struct lame_ctx));
    printf("#define LAME_CTX_R13 %zu\n", offsetof(struct lame_ctx, r13));
    printf("#define LAME_CTX_VALID %zu\n", offsetof(struct lame_ctx, valid));
    printf("#define LAME_CTX_RSP %zu\n", offsetof(struct lame_ctx, rsp));
    printf("#define LAME_CTX_RIP %zu\n", offsetof(struct lame_ctx, rip));
    printf("#define LAME_CTX_RFLAGS %zu\n", offsetof(struct lame_ctx, rflags));
    printf("#define LAME_CTX_RAX %zu\n", offsetof(struct lame_ctx, rax));
    printf("#define LAME_CTX_RBX %zu\n", offsetof(struct lame_ctx, rbx));
    printf("#define LAME_CTX_RCX %zu\n", offsetof(struct lame_ctx, rcx));
    printf("#define LAME_CTX_RDX %zu\n", offsetof(struct lame_ctx, rdx));
    printf("#define LAME_CTX_RSI %zu\n", offsetof(struct lame_ctx, rsi));
    printf("#define LAME_CTX_RDI %zu\n", offsetof(struct lame_ctx, rdi));
    printf("#define LAME_CTX_RBP %zu\n", offsetof(struct lame_ctx, rbp));
    printf("#define LAME_CTX_R8 %zu\n", offsetof(struct lame_ctx, r8));
    printf("#define LAME_CTX_R9 %zu\n", offsetof(struct lame_ctx, r9));
    printf("#define LAME_CTX_R10 %zu\n", offsetof(struct lame_ctx, r10));
    printf("#define LAME_CTX_R11 %zu\n", offsetof(struct lame_ctx, r11));
    printf("#define LAME_CTX_R12 %zu\n", offsetof(struct lame_ctx, r12));
    printf("#define LAME_CTX_R14 %zu\n", offsetof(struct lame_ctx, r14));
    printf("#define LAME_CTX_R15 %zu\n", offsetof(struct lame_ctx, r15));
    printf("#define LAME_CTX_IN_USE %zu\n\n", offsetof(struct lame_ctx, in_use));

    // macros
    printf("#define LAME_COROUTINE_DEPTH %d\n", LAME_COROUTINE_DEPTH);
    printf("#define LAME_COROUTINE_INC_MASK %d\n", LAME_COROUTINE_DEPTH - 1);
    printf("#define LAME_MAX_CPU_CORES %d\n\n", LAME_MAX_CPU_CORES);

    printf("#ifndef LAME_ASM_STORAGE\n");
    printf("#define LAME_ASM_STORAGE\n");
    printf(".section .data\n");
    printf("    .align 64\n");
    printf("    .globl lame_handle_array\n");
    printf("    .type lame_handle_array, @object\n");
    printf("lame_handle_array:\n");
    printf("    .zero %zu\n", sizeof(lame_handle_array));
    printf("    .size lame_handle_array, %zu\n", sizeof(lame_handle_array));
    printf("#endif\n");

    printf("\n#endif /* LAME_DATA_ASM_H */\n");
    printf("/* end */\n");
    return 0;
} 
/* end */